quarkus:
  application:
    name: azide-splash
  datasource:
    db-kind: postgresql
  hibernate-orm:
    database:
      generation: update
  oidc:
#    auth-server-url: http://localhost:8085/realms/quarkus
    client-id: azide
    application-type: web-app
    logout:
      path: /logout
      post-logout-path: /
#      credentials:
#        secret: secret
  http:
    port: 8081
    auth:
      permission:
        logout:
          paths: ${quarkus.oidc.logout.path}
          policy: authenticated
  container-image:
    group: "dcgs"
"%dev":
  quarkus:
    http:
      port: 8081
    log:
      level: DEBUG
    hibernate-orm:
      database:
        generation: drop-and-create
    oidc:
      auth-server-url: http://localhost:8085/realms/quarkus
      client-id: azide
      credentials:
        secret: secret
  timezones:
    identifiers:
    - "America/New York"
    - "Asia/Kuwait"
    - "Asia/Pyongyang"
  linkCategories:
    categories:
    - categoryName: Search
      links:
        - name: Google 1
          address: http://google.com
        - name: Google 2
          address: http://yahoo.com
    - categoryName: News
      links:
        - name: CNN
          address: http://cnn.com
        - name: Fox
          address: http://foxnews.com