quarkus:
  application:
    name: message-service
  datasource:
    db-kind: sqlite
  hibernate-orm:
    database:
      generation: update
  oidc:
    client-id: messageViewer
    application-type: web-app
    logout:
      path: /logout
      post-logout-path: /
  http:
    auth:
      permission:
        logout:
          paths: ${quarkus.oidc.logout.path}
          policy: authenticated
  container-image:
    group: "dcgs"
"%dev":
  quarkus:
    http:
      port: 8081
    log:
      level: DEBUG
    datasource:
      jdbc:
        url: "jdbc:sqlite::memory:"
#      db-kind: postgresql/
    hibernate-orm:
      database:
        generation: drop-and-create